-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 15:32:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema progWeb
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userEmail` VARCHAR(100) NOT NULL,
  `userPassword` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  UNIQUE INDEX `userEmail_UNIQUE` (`userEmail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleId`),
  UNIQUE INDEX `roleName_UNIQUE` (`roleName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Modules` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Modules` (
  `moduleId` INT NOT NULL AUTO_INCREMENT,
  `moduleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`moduleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsersRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UsersRoles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UsersRoles` (
  `userId` INT NOT NULL,
  `roleId` INT NOT NULL,
  `userRoleId` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Users_has_Roles_Roles1_idx` (`roleId` ASC) VISIBLE,
  INDEX `fk_Users_has_Roles_Users_idx` (`userId` ASC) VISIBLE,
  PRIMARY KEY (`userRoleId`),
  CONSTRAINT `fk_Users_has_Roles_Users`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Roles_Roles1`
    FOREIGN KEY (`roleId`)
    REFERENCES `mydb`.`Roles` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Permissions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Permissions` (
  `moduleId` INT NOT NULL,
  `roleId` INT NOT NULL,
  `permissionsId` INT NOT NULL AUTO_INCREMENT,
  `canCreate` TINYINT NOT NULL DEFAULT 0,
  `canRead` TINYINT NOT NULL DEFAULT 0,
  `canUpdate` TINYINT NOT NULL DEFAULT 0,
  `canDelete` VARCHAR(45) NOT NULL DEFAULT 0,
  INDEX `fk_Modules_has_Roles_Roles1_idx` (`roleId` ASC) VISIBLE,
  INDEX `fk_Modules_has_Roles_Modules1_idx` (`moduleId` ASC) VISIBLE,
  PRIMARY KEY (`permissionsId`),
  CONSTRAINT `fk_Modules_has_Roles_Modules1`
    FOREIGN KEY (`moduleId`)
    REFERENCES `mydb`.`Modules` (`moduleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modules_has_Roles_Roles1`
    FOREIGN KEY (`roleId`)
    REFERENCES `mydb`.`Roles` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
